### ISSUE TITLE
Cohere Error When Uploading Unknown Files

### ISSUE THREAD

**Issue by Chere3** [pye-community/pye-community-bot#43]
---

### Cohere Error When Uploading Unknown Files

An error occurs in Cohere when attempting to upload files of unknown or unsupported formats. This issue needs investigation and resolution to ensure smooth file handling within Cohere.

**Stack Trace:**
```
DiscordAPIError[10008]: Unknown Message
...
at execute (G:\00_Programacion2023\PyE-Community\src\events\threadCreate.ts:14:7)
```

**Tasks:**
- [x] Identify the unsupported file formats triggering the error.
- [x] Investigate the cause of the DiscordAPIError[10008].
- [x] Implement a fix to manage or filter unknown file formats.
- [x] Test the fix with various file formats to ensure the error is resolved.
---
